#+TITLE: Dirgahayu is Back!
#+LAYOUT: post
#+TAGS: dirgahayu malaysia rock mathrock instrumentalrock
#+AUTHOR: Alvin Sim
#+DATE: 2020-09-20
#+PUBLISHED: true

Dirgahayu, Malaysia's instrumental rock group, has just announced their new song on Malaysia Day (/16 September, 2020/), Ilhak.

#+liquid: enabled
{% include youtube.html id='4vw2fhtEdtg' %}

It was early 2020 that I became a fan of Dirgahayu, listening to their songs and watching almost all their performances that I can find on YouTube. This all started after watching their performance on "/Live on The Wknd Sessions/" on YouTube. They performed three songs -- /几 / 十 六 (Kyu / Ju Roku), Istinggar and Volumetric/.

Although many would say Dirgahayu is a [[https://en.wikipedia.org/wiki/Math_rock][math rock]] group, but as [[http://www.zulhezan.com/][Zulhezan]] highlighted in the interview on the Wknd Sessions, Dirgahayu is an instrumental rock group. They began as a trio in 2013 with Zulhezan, Afifi Rahim and Wan Azry and Seikan Sawaki joined in 2014 as the fourth member. With Seikan on the drums, Zul is able to focus on the guitar.

It wasn't until I watched [[https://www.youtube.com/watch?v=66JwskOHpdY][LIVE // Dirgahayu Farewell Show di ATAS / Seikan Sawaki's Departure - Part 1]], that I realised Seikan left the group to return to Japan. It was an emotional performance, for sure, and it's sad to see Dirgahayu without Seikan on the drums. Following that, and as I also got to know when writing this, Zul left the group in 2018. No wonder there were no news about the group since then. Even their website is no longer available. The one I have linked here is the one I found in [[https://archive.org][archive.org]]. Dirgahayu now comprises of Afifi, Tiong and Wan Azry, as listed on their bandcamp page.

Knowing this and listening to their songs on their Commemorate! album and Ilkhak again, and I can't help to feel that Ilhak does sounds different. Still a good song, nevertheless, and a good start for a new chapter for the group.

With the new member and song, lets hope that they come up with more good materials. Below are the performance they did on The Wknd with three of my favourite Dirgahayu songs. Although it's old, but still it's the best one I could find on YouTube thanks to The Wknd team for the amazing audio and video.

#+liquid: enabled
{% include youtube.html id='NOh-JZQwIos' %}

#+liquid: enabled
{% include youtube.html id='RJP3phyrJ7Q' %}

#+liquid: enabled
{% include youtube.html id='zEvQlRGEuB0' %}

If you like Dirgahayu, want to know more and support them, do follow them (/links below/). As for this post, like, share, leave a comment and subscribe (/to the RSS feeds/).

* Links

- [[https://web.archive.org/web/20190710052700/https://drghy.org/][Dirgahayu: website (/from archive.org/)]]
- [[https://www.youtube.com/channel/UC9-1cWtAW_5X1VWMd7oSBJg][Dirgahayu: YouTube channel]]
- [[https://www.facebook.com/drghyorg/][Dirgahayu: Facebook Page]]
- [[https://www.instagram.com/drghy/][Dirgahayu: Instagram]]
- [[https://twitter.com/drghyorg][Dirgahayu: Twitter]]
- [[https://soundcloud.com/drghy][Dirgahayu: Soundcloud]]
- [[https://drghy.bandcamp.com/][Dirgahayu: bandcamp]]
- [[https://open.spotify.com/artist/2N0Tje3ONakrCpnmXkwsrD][Dirgahayu: Spotify]]
- [[https://www.instagram.com/tiong.faizal/][Tiong: Instagram]]
- [[http://www.zulhezan.com/][Zulhezan: website]]
- [[https://twitter.com/nazehluz][Zulhezan: Twitter]]
- [[https://www.instagram.com/zulhezan/][Zulhezan: Instagram]]
- [[https://soundcloud.com/zulhezan][Zulhezan: Soundcloud]]

* References

1. [[https://www.youtube.com/watch?v=lxjtyGXgvuw][YouTube: Dirgahayu | Interview (Exclusive on The Wknd Sessions, #94)]]

2. [[https://web.archive.org/web/20140511184659/http://www.the-wknd.com:80/news/5-questions-dirgahayu/][The Wknd -- 5 Questions: Dirgahayu (/from archive.org/)]]

3. [[https://www.nme.com/en_asia/news/music/dirgahayu-end-hiatus-with-new-single-ilhak-2756093][NME: Dirgahayu end hiatus with new single 'ILHAK']]

4. [[https://www.facebook.com/watch/?v=1356736474512155&extid=jXq1zGN96DJn0dho][Facebook: Dirgahayu annoucing their new drummer, @tiong.faizal]]
